### PR TITLE
added display instructions on how to re-open the wizard

### LINKED ISSUE #91: Display instructions on how to re-open the wizard
At the bottom of the wizard, display instructions how to reopen the wizard by using the command palette and the "Granite: Setup Granite Code as code assistant" command, in a smaller font

### PR DESCRIPTION
**Pull request by lavanyaj3**
added display instructions on how to re-open the wizard

### CODE REVIEW

**Comment by fbricon** [comment]
No the changes belong to app.tsx, with styles going into app.css

**Comment by fbricon** [comment]
please rebase your branch against main

**Comment by lavanyaj3** [comment]
@fbricon done rebase. Its already up to date

**Comment by lavanyaj3** [comment]
i rebased again. Can you please check now.

**Comment by fbricon** [comment]
"git rebase main" still fails

**Comment by lavanyaj3** [comment]
Raised another PR for this issue .
PR number : #119

**Comment by fbricon** [comment]
Closed in favour of #119

**Pull request closed without merging**
